# Generated by Django 4.2.2 on 2023-07-22 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fastzooapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
    ]
